CREATE TABLE tblDBVersion (
	Major	INTEGER,
	Minor	INTEGER
);

INSERT INTO tblDBVersion VALUES (0,17);

CREATE TABLE tblIdentity (
	IdentityID			INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	PublicKey			VARCHAR(120) UNIQUE,
	Name				VARCHAR(60),
	SingleUse			SMALLINT DEFAULT 0 NOT NULL,
	PublishTrustList	SMALLINT DEFAULT 0 NOT NULL,
	PublishBoardList	SMALLINT DEFAULT 0 NOT NULL,
	FreesiteEdition		INTEGER,
	DateAdded			TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	LastSeen			TIMESTAMP,
	AddedMethod			VARCHAR(255),
	FailureCount 		INTEGER DEFAULT 0 NOT NULL CHECK(FailureCount>=0)
);

CREATE TABLE tblPeerTrust(
	IdentityID				INTEGER NOT NULL,
	TargetIdentityID		INTEGER NOT NULL,
	MessageTrust			INTEGER CHECK(MessageTrust BETWEEN 0 AND 100),
	TrustListTrust			INTEGER CHECK(TrustListTrust BETWEEN 0 AND 100),
	MessageTrustComment		VARCHAR(80),
	TrustListTrustComment	VARCHAR(80),
	PRIMARY KEY (IdentityID,TargetIdentityID),

	CONSTRAINT xtblPeerTrustTrustIdentityID FOREIGN KEY(IdentityID) REFERENCES tblIdentity(IdentityID) ON DELETE CASCADE,
	CONSTRAINT xtblPeerTrustTrustTargetIdentityID FOREIGN KEY(TargetIdentityID) REFERENCES tblIdentity(IdentityID) ON DELETE CASCADE
);

CREATE INDEX idxPeerTrust_IdentityID ON tblPeerTrust (IdentityID);

CREATE INDEX idxPeerTrust_TargetIdentityID ON tblPeerTrust (TargetIdentityID);

CREATE TABLE tblBoard(
	BoardID					INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	BoardName               VARCHAR(60) UNIQUE NOT NULL,
	BoardDescription        VARCHAR(127),
	DateAdded               TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	Subscribe				SMALLINT DEFAULT 1 NOT NULL
);

CREATE TABLE tblMessage (
	MessageID		INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	UUID			VARCHAR(90) NOT NULL,
	IdentityID		INTEGER NOT NULL,
	ReplyBoard		INTEGER NOT NULL,
	PostTime		TIMESTAMP NOT NULL,
	Subject			VARCHAR(120),
	Body			CLOB,
	CONSTRAINT xtblMessageIdentityID FOREIGN KEY(IdentityID) REFERENCES tblIdentity(IdentityID) ON DELETE CASCADE,
	CONSTRAINT xtblMessageReplyBoard FOREIGN KEY(ReplyBoard) REFERENCES tblBoard(BoardID)
);

CREATE INDEX idxMessage_UUID ON tblMessage (UUID);

CREATE TABLE tblMessageParent (
	MessageID		INTEGER,
	ParentOrder		INTEGER CHECK (ParentOrder >=0),
	ParentUUID		VARCHAR(90) NOT NULL,
	ParentMessageID		INTEGER,
	PRIMARY KEY (MessageID,ParentOrder),
	CONSTRAINT xtblMessageParentID FOREIGN KEY(MessageID) REFERENCES tblMessage(MessageID),
	CONSTRAINT xtblMessageParentParentID FOREIGN KEY(MessageID) REFERENCES tblMessage(MessageID)
);

CREATE INDEX idxMessageParentParentUUID ON tblMessageParent(ParentUUID);
CREATE INDEX idxMessageParentParentMessageID ON tblMessageParent(ParentMessageID);

CREATE TABLE tblMessageBoards (
	MessageID		INTEGER,
	BoardID			INTEGER,
	PRIMARY KEY (MessageID,BoardID),
	CONSTRAINT xtblMessageBoardsID FOREIGN KEY(MessageID) REFERENCES tblMessage(MessageID) ON DELETE CASCADE,
	CONSTRAINT xtblMessageBoardsBoard FOREIGN KEY(BoardID) REFERENCES tblBoard(BoardID)
);

CREATE TABLE tblMessageAttachment (
	MessageID		INTEGER,
	CHK				VARCHAR(512),
	PRIMARY KEY (MessageId,CHK),
	CONSTRAINT xtblMessageAttachmentId FOREIGN KEY(MessageID) REFERENCES tblMessage(MessageID) ON DELETE CASCADE
);

CREATE TABLE tblIdentityRequests(
	IdentityID		INTEGER,
	Day				DATE,
	RequestIndex	INTEGER,
	FailureCount	INTEGER DEFAULT 0 NOT NULL,
	Loaded			INTEGER DEFAULT 0 NOT NULL,
	PRIMARY KEY (IdentityID, Day, RequestIndex),
	CONSTRAINT xtblIdentityRequestsIdentityID FOREIGN KEY(IdentityID) REFERENCES tblIdentity(IdentityID) ON DELETE CASCADE
);

CREATE TABLE tblTrustListRequests(
	IdentityID		INTEGER,
	Day				DATE,
	RequestIndex	INTEGER,
	FailureCount	INTEGER DEFAULT 0 NOT NULL,
	Loaded			INTEGER DEFAULT 0 NOT NULL,
	PRIMARY KEY (IdentityID, Day, RequestIndex),
	CONSTRAINT xtblTrustListRequestsIdentityID FOREIGN KEY(IdentityID) REFERENCES tblIdentity(IdentityID) ON DELETE CASCADE
);

CREATE TABLE tblBoardListRequests(
	IdentityID		INTEGER,
	Day				DATE,
	RequestIndex	INTEGER,
	FailureCount	INTEGER DEFAULT 0 NOT NULL,
	Loaded			INTEGER DEFAULT 0 NOT NULL,
	PRIMARY KEY (IdentityID, Day, RequestIndex),
	CONSTRAINT xtblBoardListRequestsIdentityID FOREIGN KEY(IdentityID) REFERENCES tblIdentity(IdentityID) ON DELETE CASCADE
);

CREATE TABLE tblMessageListRequests(
	IdentityID		INTEGER,
	Day				DATE,
	RequestIndex	INTEGER,
	FailureCount	INTEGER DEFAULT 0 NOT NULL,
	Loaded			INTEGER DEFAULT 0 NOT NULL,
	PRIMARY KEY (IdentityID, Day, RequestIndex),
	CONSTRAINT xtblMessageListRequestsIdentityID FOREIGN KEY(IdentityID) REFERENCES tblIdentity(IdentityID) ON DELETE CASCADE
);

CREATE TABLE tblMessageRequests(
	IdentityID		INTEGER,
	SourceIdentityID	INTEGER,
	Day				DATE,
	RequestIndex	INTEGER,
	FailureCount	INTEGER DEFAULT 0 NOT NULL,
	Loaded			INTEGER DEFAULT 0 NOT NULL,
	PRIMARY KEY (IdentityID, Day, RequestIndex),
	CONSTRAINT xtblMessageRequestsIdentityID FOREIGN KEY(IdentityID) REFERENCES tblIdentity(IdentityID) ON DELETE CASCADE,
	CONSTRAINT xtblMessageRequestsSourceIdentityID FOREIGN KEY(SourceIdentityID) REFERENCES tblIdentity(IdentityID) ON DELETE CASCADE
);

INSERT INTO tblIdentity(PublicKey,AddedMethod) VALUES('SSK@NuBL7aaJ6Cn4fB7GXFb9Zfi8w1FhPyW3oKgU9TweZMw,iXez4j3qCpd596TxXiJgZyTq9o-CElEuJxm~jNNZAuA,AQACAAE/','Seed Identity');

INSERT INTO tblIdentity(PublicKey,AddedMethod) VALUES('SSK@IxVqeqM0LyYdTmYAf5z49SJZUxr7NtQkOqVYG0hvITw,RM2wnMn5zAufCMt5upkkgq25B1elfBAxc7htapIWg1c,AQACAAE/','Seed Identity');

INSERT INTO tblIdentity(PublicKey,AddedMethod) VALUES('SSK@bloE1LJ~qzSYUkU2nt7sB9kq060D4HTQC66pk5Q8NpA,DOOASUnp0kj6tOdhZJ-h5Tk7Ka50FSrUgsH7tCG1usU,AQACAAE/','Seed Identity');

INSERT INTO tblIdentity(PublicKey,AddedMethod) VALUES('SSK@Ofm~yZivDJ5Z2fSzZbMiLEUUQaIc0KHRdZMBTaPLO6I,WLm4s4hNbOOurJ6ijfOq4odz7-dN7uTUvYxJRwWnlMI,AQACAAE/','Seed Identity');

INSERT INTO tblIdentity(PublicKey,AddedMethod) VALUES('SSK@aYWBb6zo2AM13XCNhsmmRKMANEx6PG~C15CWjdZziKA,X1pAG4EIqR1gAiyGFVZ1iiw-uTlh460~rFACJ7ZHQXk,AQACAAE/','Seed Identity');
